### ISSUE TITLE
Ftrack helm package: event-scheduler, server, worker does not starting

### ISSUE THREAD

**Issue by AloySobek** [AloySobek/ftrack-stub#1]
Hi! On the last week we've tried to install ftrack helm package into our Kubernetes cluster and we've faced with some problems because of which we still cannot run ftrack server. If in values.yaml file we set database.autoUpgrade flag to true, then Job resource fail every time. Job pod does not show any logs so we don't understand why it's happening. Long story short - some Deployments does not starting, for example all 5 server replicas fail with “!!! uWSGI process 1 got Segmentation Fault !!!” log. Most interesting  - this is all we can get from failed deployments. Event-scheduler and worker replicas does not show any logs at all.

### Environment
OS Version:
```
Distributor ID: Debian
Description: Debian GNU/Linux 10 (buster)+
Release: 10
Codename: buster
```
Kubernetes Version:
```
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
We have a bare metal Kubernetes with 3 nodes.
No specific configuration on nodes, only static network
Cluster has been deployed via Kubespray v2.15.0 with almost default configuration:

Kubespray config:
```
containerd_use_systemd: true
container_manager: containerd\n
dashboard_enabled: true
ingress_ambassador_enabled: true
metallb_enabled: true
```
According to official instructions, we installed external mariadb with sample database and checked that we can connect to it within the cluster:

```
kubectl run mariadb -i --tty --image=mariadb:10.3 --restart=Never --rm -- /bin/bash
mysql -h IP_ADDRESS_OF_MARIADB -u user -p -e 'select username from ftrack.user'
+----------+
| username |
+----------+
| demo1    |
| demo2    |
| demo3    |
| demo4    |
| root     |
+----------+
```
As well we have an nfs storage with sample data in it:
```
ls -al data

total 16
drwxr-xr-x  4     500     500 4096 Feb 24 00:47 .
drwxr-xr-x  6    user    user 4096 Feb 23 20:41 ..
drwxrwxrwx 18     500     500 4096 Feb 10  2020 attachments
drwxrwxrwx  2     500     500 4096 Feb 23 20:50 tmp
```
Values.yaml configuration file for ftrack helm package:
```
---
secret: Generated with python -c 'import uuid;print uuid.uuid4()'
url: "http://ftrack.100-kwt.ru"
database:
  host: database_host
  name: ftrack
  user: user
  password: pass
imageRegistry:
  password: REAL_PASSWORD_HERE
nfsPersistentVolume:
  enabled: true
  path: /
  server: valid_nfs_host_with_sample_data
  size: 30Gi
```
